---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8080
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: backend
        image: quay.io/datawire/quote:0.3.0
        ports:
        - name: http
          containerPort: 8080
